### ISSUE TITLE
replacement of GCP configuration ?

### ISSUE THREAD

**Issue by rabihbeyrouty** [madeindra/signal-setup-guide#44]
Server Version : Server v3.21

Dependencies : GCP 

is there any replacement of GCP configuration inside the config.yml , because it same as S3 amazon need subscription 

thanks and regards,

**Comment by madeindra** [comment]
@rabihbeyrouty I personally use something like this, it is because I use minio for attachment

```yaml
gcpAttachments: # gcp storage configuration
  domain: domain.com 
  email: dummy@dummy.com
  maxSizeInBytes: 1000000
  pathPrefix: /
  rsaSigningKey: "-----BEGIN RSA PRIVATE KEY-----\r\n ...  \r\n-----END RSA PRIVATE KEY-----"
```
